/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.BulletsModelTestCase;
	import flexUnitTests.ShipsModelTestCase;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_ShipsModelTestCase_obj:flexUnitTests.ShipsModelTestCase;
		
		private var flexUnitTests_BulletsTestCase_obj:flexUnitTests.BulletsModelTestCase;
	}
}